/**
 * NA Hub Transfers Restricted Dates API Spec
 * No description available
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */

import { ModelString } from './modelString';


export interface RestrictedDates { 
    ["restrictedDates"]?: ModelString;
    ["startDate"]?: string;
    ["endDate"]?: string;
}

